http:
  port: 8080
admin:
  port: 9876
  hostname: localhost
apiEndpoints:
  api:
    host: localhost
    paths: '/ip'
  hydrometries-api:
    host: localhost
    paths: ['/hydrometries', '/hydrometries/*']
serviceEndpoints:
  httpbin:
    url: 'https://httpbin.org'
  hydrometries-service:
    url: ${HYDROMETRIES_API_URL}
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
pipelines:
  default:
    apiEndpoints:
      - api
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: httpbin
              changeOrigin: true
  hydrometries:
    apiEndpoints:
      - hydrometries-api
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - log: # policy name
        - action:    # array of condition/actions objects
            message: ${req.method} ${req.originalUrl}
      - proxy:
          - action:
              serviceEndpoint: hydrometries-service
              changeOrigin: true